---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3298474769-I17uPmOeE6SfFd8LCRcXGbZORPcKtrQEW6oPqAF
:access_token_secret: hTA67d5VHjlHdsl39bcs7OrHtXAnBaFxdu0awzrqCITt1
